Add non standard fields
inbo/camtraptor pull request #186
Opened 2022-12-22 20:36 UTC by damianooldoni

This PR solves #185 and #182.
I have been quite conservative in solving #185 to avoid errors in case of renaming non-existing columns.
I do not trigger any warning but I inform the user about non standard fields by returning three messages on console:

```r
Non standard field after _id found: renamed to speed.                                                                 
Non standard field after _id found: renamed to radius.
Non standard field after _id found: renamed to angle.
```

2022-12-22 21:04 UTC, damianooldoni commented
Tests are failing due to https://github.com/tdwg/camtrap-dp/issues/269.

2022-12-23 09:57 UTC, peterdesmet requested changes
I would not test these columns separately but together:

    if (c("X22", "X23", "X24") %in% names(observations))

And return a single warning:

> Three extra fields in `observations` interpreted as `speed`, `radius` and `angle`.

In the test file, I would not prepend all functions with `testthat::`. I haven't seen that being done in other packages (including ours) and it just makes the code more verbose.

2022-12-23 10:23 UTC, damianooldoni commented
Thanks @peterdesmet. About testing the columns together: are we ALWAYS sure that these 3 columns come up all together in a camtrap datapackage?

I was prepending `testthat::` as we started to prepend the package name to all functions throughout all our packages. So, I was thinking it was something useful for test files as well. But you are right. It seems not standard to do it in tests.

2022-12-23 10:25 UTC, peterdesmet commented
> are we ALWAYS sure that these 3 columns

Pretty much, as we control how they are coming out of Agouti.

2022-12-23 10:29 UTC, damianooldoni commented
Ok. For this time I will be less defensive and less verbose 😃

2022-12-23 10:41 UTC, peterdesmet approved these changes

2022-12-23 11:04 UTC, merged