Remove media arg
inbo/camtraptor pull request #272
Opened 2023-09-04 10:19 UTC by damianooldoni

Solving #255.

2023-09-04 12:24 UTC, damianooldoni commented
Note to me: after PR #269 and #271 are merged to v1.0:
1. Pull changes from v1.0 to my branch
2. Add line to `NEWS.md`
3. Set reviewer

2023-09-05 09:04 UTC, damianooldoni commented
Note for me: after PR #271 has been merged to `v1.0`, please merge it to this branch and add a line in `news.md`.

2023-09-06 09:01 UTC, PietrH requested changes

2023-09-06 09:01 UTC, PietrH commented on tests/testthat/test-read_camtrap_dp.R
>        names()
You could use `expect_named()` in the code block below, but since the tests are for specific fields I'm also ok with leaving this as is. It's a tradeoff between the test being readable, or the message when it fails.

2023-09-06 09:01 UTC, PietrH commented on tests/testthat/test-read_camtrap_dp.R
> +    dp_with_media <- suppressMessages(read_camtrap_dp(file = dp_path))
Again, not sure if we need to keep reading this file. I think we should read it outside of a test body as setup and reuse the object `dp_with_media`, that'll make it easier to maintain as well.

2023-09-06 09:04 UTC, PietrH commented
@damianooldoni , I've made some suggestions, could you also look at bb04e3c15d0510bbbabc5884b3e5230dddbc8600? Using `writeLines()` results in the messages not being silenced by `suppressMessages() `.

In summary:

- Consider using `expect_type()` and `expect_s3_class()` where possible
- Consider using `expect_named()` where it makes sense
- Lets try to reuse objects where possible, this way it's easier to make changes later, and it saves time running the tests

2023-09-06 09:33 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +  expect_true(is.list(dp_with_media))
The point is that a data.frame would pass this test as well. The most elegant solution is to use `rlang::is_bare_list()`, as @PietrH found.

2023-09-06 09:46 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +  expect_true("data" %in% names(dp_with_media))
Great! This will help us to detect changes while reading datapackages with newer versions of camtrap-dp.

2023-09-06 10:13 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +    dp_with_media <- suppressMessages(read_camtrap_dp(file = dp_path))
I get your point. I think it's better to leave it as it is at the moment: it will change anyhow while working on #220 as we will remove all datapackages in `inst/extdata`.

2023-09-06 10:40 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
>      expect_equal(cols_deployments_dp_v0_1_6, cols_deployments_dp_v1_rc1)
Replaced everywhere in this test file.

2023-09-06 11:47 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
>    expect_true("data" %in% names(dp_v1_rc1_with_media))
Done

2023-09-06 11:54 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
>    expect_true(all(c("tbl_df", "tbl", "data.frame") %in%
Done in [e762ca9](https://github.com/inbo/camtraptor/pull/272/commits/e762ca9400c2ab2dcc31b68b42ab4dbc1fa59ddd)

2023-09-06 11:55 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
>    expect_true(all(c("tbl_df", "tbl", "data.frame") %in%
Solved in same commit as previous conversation: [e762ca9](https://github.com/inbo/camtraptor/pull/272/commits/e762ca9400c2ab2dcc31b68b42ab4dbc1fa59ddd)

2023-09-06 12:50 UTC, merged