Use calendar values in `get_custom_effort`
inbo/camtraptor pull request #278
Opened 2023-09-06 12:55 UTC by damianooldoni

This PR solves #219 by using calendar weeks/months/years for grouping while calculating the effort.

Unit-tests in `test-get_custom_effort()` have been not only updated, but also sensibly improved partly based on testthat things learned while working on #272 thanks to @PietrH.

2023-09-06 12:57 UTC, damianooldoni commented
Notice that we consider this work as a hotfix, so version is bumped to 0.20.1.

2023-09-06 15:19 UTC, PietrH requested changes
Looks great, a very quick turnaround, well done 🚀

Checks out, I ran `devtools::document()` and committed. I also fixed some trailing whitespace in the test file, and noticed you are inconsistent in capitalizing your comments in the function source.

2023-09-06 15:19 UTC, PietrH commented on R/get_custom_effort.R
> +      dplyr::group_by(begin) %>%
`no visible binding for global variable ‘begin’`

```suggestion
      dplyr::group_by(.data$begin) %>%
```

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +
```suggestion

```

remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +
```suggestion

```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +    lubridate::floor_date(first_day, unit = "weeks"),
```suggestion
    lubridate::floor_date(first_day, unit = "weeks"),
```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +    lubridate::floor_date(first_day, unit = "months"),
```suggestion
    lubridate::floor_date(first_day, unit = "months"),
```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +    lubridate::floor_date(first_day, unit = "years"),
```suggestion
    lubridate::floor_date(first_day, unit = "years"),
```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +                   "`end` value must be not earlier than the start of the ",
```suggestion
                   "`end` value must be not earlier than the start of the ",
```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +                    "earlier than the start of the earliest deployment: ",
```suggestion
    get_custom_effort(mica,
                      start = as.Date("2021-01-01"),
                      end = as.Date("1990-01-01")),
    regexp = paste0("`end` value is set too early. `end` value must be not ",
                    "earlier than the start of the earliest deployment: ",
```
remove trailing whitespace

2023-09-06 15:19 UTC, PietrH commented on tests/testthat/test-get_custom_effort.R
> +                               "Valid inputs are: NULL, day, week, month ",
```suggestion
               regexp = paste0("Invalid value for group_by parameter: ",
                               "bad_value.\n",
                               "Valid inputs are: NULL, day, week, month ",
```
remove trailing whitespace

2023-09-07 08:27 UTC, damianooldoni commented on R/get_custom_effort.R
> +      dplyr::group_by(begin) %>%
Yes, I forgot it! Thanks.

2023-09-07 08:35 UTC, damianooldoni commented
Thank you for the review! I will now check all comments are capitalized. Next time, remove directly the whitespaces in a commit, if you wish. I think it will save time for both. But many thanks to finding them.

2023-09-07 10:05 UTC, PietrH approved these changes

2023-09-07 10:12 UTC, PietrH commented
Thanks for the changes. Good job! I'll commit small stylistic changes directly next time. 

Ok to merge!

2023-09-07 12:57 UTC, merged