Inherit parsing issues
inbo/camtraptor pull request #282
Opened 2023-09-29 19:41 UTC by damianooldoni

This PR is quite small and is a small patch to solve a small bug noticed by @jimcasaer. While reading a datapackage, a warning about parsing issues in deployments was returned on screen. However, nothing was returned by readr::problems(dp$data$deployments)`.

The reason? While working on v0.20 I removed by accident the few lines of code where I assigned reading issues of deployments and media to the attributes of the corresponding data.frames.

2023-09-29 19:46 UTC, damianooldoni commented
Improving tests at the moment...

2023-10-01 07:21 UTC, damianooldoni commented
Still getting failing check on Ubuntu-latest (3.6.3). It's an issue with the installation of terra package.
https://github.com/inbo/camtraptor/actions/runs/6356494664/job/17288425829?pr=282#step:5:4726

@pietrH; if you agree, I would remove (temporarily?) this check. We have already a windows-latest (3.6.0) check to ensure compatibility with R 3.6.x.

2023-10-02 09:03 UTC, PietrH commented
`test-read_camtrap_dp.R` does print some messages to console during testing, this is because in `zzz.R`:

https://github.com/inbo/camtraptor/blob/d79224fd87f9e722425b4e6feb9d40a3c3b6df4a/R/zzz.R#L464-L471

We use `writeLines()` to print to console, not `warning()` or `message()`, this slightly different approach results in `suppressMessages(read_camtrap_dp())` still printing to console while testing.

2023-10-02 09:12 UTC, PietrH commented
> Still getting failing check on Ubuntu-latest (3.6.3). It's an issue with the installation of terra package. https://github.com/inbo/camtraptor/actions/runs/6356494664/job/17288425829?pr=282#step:5:4726
> 
> @PietrH; if you agree, I would remove (temporarily?) this check. We have already a windows-latest (3.6.0) check to ensure compatibility with R 3.6.x.

It seems to be fixed in the current development build of terra: https://github.com/rspatial/terra/issues/1276

They were using the new anonymous functions introduced in R4.1, altough it surprises me that our tests passed on Windows 3.6.0

Originally I was thinking about a problem with different line breaks between Linux and Windows, similar to: https://stackoverflow.com/questions/56471638/error-unable-to-collate-and-parse-r-files-for-package-upload-to-cran

---

In principle I don't protest removing the check on Ubuntu, however, are should make sure we aren't accidentally (re-)discovering a lingering issue in terra.

2023-10-02 09:44 UTC, PietrH commented
Some things I fixed in commits:

- moved creation of objects needed for tests to very first line of test script, is clearer to contributes (fooled me!) that these objects are created if they are running tests out of order 
- replaced `expect_equal(class())` with `expect_type()`, also consider `expect_s3_class()`: easier to read, less error prone
- replace `expect_equal(length())` with `expect_length()`: easier to read
- replaced `expect_equal()` with `expect_identical()` where I felt it was a better match, increasing test strictness. `expect_equal()` has a built in tolerance. 

in `test-read_camtrap_dp.R` we are reusing even objects between tests, we could put those in the start of the file as well, this way the tests will run faster, and it's easier for us to make changes in the way these objects are created.

2023-10-02 10:05 UTC, PietrH commented
One final comment: 

I'm having some trouble with this test:
https://github.com/inbo/camtraptor/blob/1b749cd1ba692b9860640ddb611f4124a32f9fc2/tests/testthat/test-read_camtrap_dp.R#L303-L319

- Why do we suppress the messages of expect_warning?
- I can't get the deprecation warning to actually show in my console, but that might be on my end as it might only show once and then not again for a few hours. 
- When running `covr` I ran into this error:

```
-- Error ('tests/testthat/test-read_camtrap_dp.R:305:3'): path is deprecated ---
Error in `lifecycle_message(when, what, with, details, env, signaller = "deprecate_warn")`: Can't detect the package of the deprecated function.
Please mention the namespace:

  # Good:
  deprecate_warn(what = "namespace::myfunction()")

  # Bad:
  deprecate_warn(what = "myfunction()")

Backtrace:
     x
  1. +-rlang::with_options(...) at tests/testthat/test-read_camtrap_dp.R:305:2
  2. +-base::suppressMessages(...)
  3. | \-base::withCallingHandlers(...)
  4. +-testthat::expect_warning(...)
  5. | \-testthat:::expect_condition_matching(...)
  6. |   \-testthat:::quasi_capture(...)
  7. |     +-testthat (local) .capture(...)
  8. |     | \-base::withCallingHandlers(...)
  9. |     \-rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
 10. \-read_camtrap_dp(file = dp_path_warning, media = FALSE)
 11.   \-lifecycle::deprecate_warn(...)
 12.     +-lifecycle:::deprecate_warn0(...)
 13.     | +-id %||% paste_line(msg)
 14.     | \-lifecycle:::paste_line(msg)
 15.     |   +-base::paste(chr(...), collapse = "\n")
 16.     |   \-rlang::chr(...)
 17.     |     \-rlang::dots_values(...)
 18.     \-lifecycle:::lifecycle_message(when, what, with, details, env, signaller = "deprecate_warn")
 19.       \-lifecycle:::spec(what, env, signaller = signaller)
 20.         \-lifecycle:::spec_pkg(what$pkg, env, ctxt = ctxt)
 21.           \-cli::cli_abort(...)
 22.             \-rlang::abort(...)

```

However the documentation https://search.r-project.org/CRAN/refmans/lifecycle/html/deprecate_soft.html mentions the namespace declaration as optional. 

@damianooldoni , could you have a look at this test to see if to works as intended?

2023-10-02 10:08 UTC, PietrH requested changes
- I made some small changes, see the comments above. 
- I'm having trouble verifying if the deprecation test works as indented. Comment above. 
- Don't forget to use testtthat convenience functions like expect_length and expect_type, they are easier to read and sometimes have other advantages too. 
- Great job, looks great. This test is getting quite big! Thank you for tackling this

2023-11-08 13:57 UTC, damianooldoni commented
Thanks @PietrH for your extended review and actively pushing! 

@PietrH: I think we could include this work in the next release. I see you mentioned this PR in #282. As #282 is much more urgent than this patch work I would proceed as following:
1. finalize #282 and merge it to `main`
2. pull changes in this branch and solve possible conflicts
3. work as much as possible on your requested changes in the tests

2023-11-08 15:06 UTC, PietrH approved these changes

2023-11-09 15:33 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
>    expect_true("data" %in% names(dp_without_media))
Only `"data"`, indeed.

2023-11-09 15:35 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +    dp_issues <- camtraptor::read_camtrap_dp(file = camtrap_dp_file_with_issues)
Agreed to use `capture_warnings` instead of `w`. See [6860d5e](https://github.com/inbo/camtraptor/pull/282/commits/6860d5e43b1cc91b7e4b454f475847d9ba96ae64)

2023-11-09 15:40 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +    dp_issues <- camtraptor::read_camtrap_dp(file = camtrap_dp_file_with_issues)
Yes, we could test the number of warnings but I think it's overshooting at the moment.

2023-11-09 15:46 UTC, damianooldoni commented on tests/testthat/test-read_camtrap_dp.R
> +    dp_issues <- camtraptor::read_camtrap_dp(file = camtrap_dp_file_with_issues)
Thinking about this a second time, actually it's not overshooting at all 👍 Done in [3696013](https://github.com/inbo/camtraptor/pull/282/commits/36960137729a1b1f9e6f14a973abe9583a887818)

2023-11-09 15:54 UTC, damianooldoni commented
Thanks @PietrH for your in depth review and for improving the coding and the quality of the tests.

@peterdesmet  and @PietrH: I didn't add anything on `NEWS.md` about this PR as it is a very small patch work. However, feel free to disagree. If so, please add please a line if you think so. Something like: 
- Solve a bug in `read_camtrap_dp()` while returning parsing issues (see #282).

I would first finalize the more important PR #289, then pulling the changes in main into this PR. I don't expect any conflict this time as PR #289 didn't modify anything related to `read_camtrap_dp()` and its tests.

2023-11-10 16:24 UTC, merged