Add logo to readme
inbo/camtraptor pull request #300
Opened 2024-03-21 14:42 UTC by PietrH

#270 created a logo for the package, this PR adds it to the readme.

2024-03-21 14:49 UTC, PietrH commented
We could consider uploading a higher quality logo, but this is not default behaviour in usethis. Probably to keep the page loading time down.

2024-03-21 15:07 UTC, PietrH commented
I'm not sure why tests are failing

2024-03-21 16:07 UTC, peterdesmet requested changes

2024-03-21 16:07 UTC, peterdesmet commented on README.Rmd
> +# camtraptor <a href="https://inbo.github.io/camtraptor"><img src="man/figures/logo.png" align="right" height="137" alt="camtraptor website" /></a>
Is it a convention to wrap the logo in a link? Why not:

```suggestion
# camtraptor <img src="man/figures/logo.png" align="right" alt="logo" width="120">
```

2024-03-29 12:50 UTC, PietrH commented on README.Rmd
> +# camtraptor <a href="https://inbo.github.io/camtraptor"><img src="man/figures/logo.png" align="right" height="137" alt="camtraptor website" /></a>
I used `usethis::use_logo()`, No idea what the reasoning behind it is.

2024-04-08 10:41 UTC, peterdesmet commented on README.Rmd
> +# camtraptor <a href="https://inbo.github.io/camtraptor"><img src="man/figures/logo.png" align="right" height="137" alt="camtraptor website" /></a>
Ok, you can leave the link. It is used to link to the website from the README in the GitHub repo. The link is removed on the pkgdown website itself.

2024-04-09 13:09 UTC, PietrH commented
Made a mockup of a version with a red background. 

![camtraptor_logo_lexend_red](https://github.com/inbo/camtraptor/assets/48065851/ed011c45-9531-405a-b326-30325496d9a2)

2024-04-09 13:28 UTC, PietrH commented
Checked with https://www.color-blindness.com/coblis-color-blindness-simulator/

2024-04-10 12:12 UTC, PietrH commented
There was a tiny issue on the right lower corner of the hexagon, where a part of the background was bleeding into the black border. I filled it in with black:

![camtraptor_logo_lexend_red_fix](https://github.com/inbo/camtraptor/assets/48065851/931e72fa-a4d7-4e76-ac35-bb68f0221fde)

I've also included the sRGB colour profile, and stored it as an interlaced PNG for quicker loading. Not sure that those changes will matter at all because `usethis` converts the image with imagemagick anyway.

2024-04-10 12:20 UTC, NeleMullens commented
Love the logo @PietrH, for me this is fine. Feels very Jurassic to me

2024-04-10 14:21 UTC, PietrH commented
Ready for review, should be able to merge if we agree on the logo.

2024-04-15 10:37 UTC, peterdesmet approved these changes
Looks fantastic! 🦖 Thanks @NeleMullens!

2024-04-15 11:30 UTC, damianooldoni approved these changes

2024-04-15 11:38 UTC, merged