Use camtrapdp to read pkgs
inbo/camtraptor pull request #307
Opened 2024-05-16 09:34 UTC by damianooldoni

*DRAFT**: not ready for review.

This PR is the first step towards version 1.0.

- Reading packages by reexporting `camtrapdp::read_camtrapdp()`.
- Deprecate `read_camtrap_dp()`.
- Remove check functions as datapackage checks are now done using `camtrapdp::check_camtrapdp()`. Remove the section about validation functions in `_pkgdown.yml` as well.
- Remove all help functions used to downconvert to 0.1.6.
- Remove help functions to add taxonomic information to `observations` data.frame as it is done by camtrapdp internally.

2024-05-21 16:59 UTC, peterdesmet commented
Have not reviewed files, just read the PR description. Regarding this:

> Adapt tests related to reading camtrap DPs. These are very minimal now as the most of the tests are within camtrapdp. We test now only that the read_camtrap_dp() returns the exact warning and that its output is identical to the output of camtrapdp::read_camtrapdp().

I would only test that the output is the same, not the warnings. Alternatively, test _only_ that a deprecation warning is returned, pointing to `read_camtrapdp()`

2024-05-22 06:10 UTC, peterdesmet requested changes

2024-05-22 07:47 UTC, damianooldoni commented on _pkgdown.yml
> -- title: Read data
Good point. This is one thing left by my first refactoring when I thought to not include the reading functionality in camtraptor. I will add it.

2024-05-22 07:48 UTC, damianooldoni commented on tests/testthat/test-read_camtrapdp.R
> +  expect_identical(read_camtrapdp(file), camtrapdp::read_camtrapdp(file))
Well, I have to test that the output of camtraptor's function is the same as the output of the camtrapdp's function, i.e. the reexport has been done correctly. So, I expect that the output of the two functions is exactly the same (identical).

2024-05-22 07:52 UTC, damianooldoni commented on NEWS.md
> +- publication functions `write_dwc()` and `write_eml()` are removed. The function `write_dwc()` has been moved to camtrapdp package. The `write_eml()` function is not needed anymore ([camtrapdp(#61)]
Nice rephrasing 🔝

2024-05-22 07:54 UTC, damianooldoni commented on tests/testthat/test-read_camtrapdp.R
> +  expect_identical(read_camtrapdp(file), camtrapdp::read_camtrapdp(file))
If my answer makes sense, feel free to resolve this conversation.

2024-05-22 08:00 UTC, peterdesmet commented on tests/testthat/test-read_camtrapdp.R
> +  expect_identical(read_camtrapdp(file), camtrapdp::read_camtrapdp(file))
Oh, this test file is a mix of `read_camtrapdp()` and `read_camtrap_dp()`. Personally, I would not test any of the reexported functions.

2024-06-06 15:03 UTC, peterdesmet requested changes

2024-06-06 15:03 UTC, peterdesmet commented on DESCRIPTION
>      frictionless,
I wonder if `frictionless` this needs to be imported still?

2024-07-03 09:49 UTC, damianooldoni commented on R/get_cam_op.R
>  #' @param package Camera trap data package object, as returned by
I agree. I would not deprecated `package` argument even. The typical user doesn't pass this argument by name as `get_*(package = )`.

2024-07-03 11:26 UTC, damianooldoni commented on R/get_cam_op.R
>  #' @param package Camera trap data package object, as returned by
I think this should be tackled in apart PR. I wrote an issue about it: https://github.com/inbo/camtraptor/issues/311

2024-07-03 11:59 UTC, damianooldoni commented on R/check_species.R
>  #' @param package Camera trap data package object, as returned by
Solved in [87460ac](https://github.com/inbo/camtraptor/pull/307/commits/87460ac6cb74a4374948ac9b713dec9af0fde653)

2024-07-03 12:08 UTC, damianooldoni commented on R/read_camtrap_dp.R
>  #' @param file Path or URL to a `datapackage.json` file.
Yes, indeed, we can do it. Done in [20c782b](https://github.com/inbo/camtraptor/pull/307/commits/20c782b0416d7feddd9f0e981ca0f577599d1676). The syntax to use is:
`#' @inheritParams packageName::functionName`

2024-07-03 12:11 UTC, damianooldoni commented on _pkgdown.yml
> -- title: Read data
Done in [fb5235e](https://github.com/inbo/camtraptor/pull/307/commits/fb5235edc8972a67bdc421d6752c665b3930dd2b)

2024-07-03 13:08 UTC, damianooldoni commented on DESCRIPTION
>      frictionless,
Indeed, not needed anymore. Removed in [064a7e3].(https://github.com/inbo/camtraptor/pull/307/commits/064a7e3e7ce9a94f0efd1b8abe36e34ce1ab8f48)

2024-07-03 13:32 UTC, damianooldoni commented on R/camtraptor-package.R
> +#' @importFrom lifecycle deprecated
Indeed. Not needed! Removed in 93c1abd.

2024-07-03 13:33 UTC, damianooldoni commented on R/camtrapdp_functions.R
It makes sense. Done in 2561536.

2024-07-03 14:19 UTC, damianooldoni commented on man/figures/lifecycle-archived.svg
Unfortunately not. From [badge documentation](https://lifecycle.r-lib.org/reference/badge.html):

> Call [usethis::use_lifecycle()](https://usethis.r-lib.org/reference/use_lifecycle.html) to copy the badge images into the man/ folder of your package.

Notice that dplyr and purrr R packages do the same, see svg files in `/man/figures` folder: 
- [dplyr](https://github.com/tidyverse/dplyr/tree/main/man/figures)
- [purrr](https://github.com/tidyverse/purrr/tree/main/man/figures)

2024-07-03 16:28 UTC, peterdesmet approved these changes

2024-07-04 06:49 UTC, PietrH approved these changes

2024-07-04 06:50 UTC, PietrH commented
I made some minor suggestions, lots of test failures.

2024-07-04 08:32 UTC, damianooldoni commented on NEWS.md
> +# camtraptor 1.0
Done in [da617fc](https://github.com/inbo/camtraptor/pull/307/commits/da617fcb9c38b235a7297d3a6d4e0ff25efe9ed3)

2024-07-04 08:32 UTC, damianooldoni commented on NEWS.md
> +
Done in https://github.com/inbo/camtraptor/commit/da617fcb9c38b235a7297d3a6d4e0ff25efe9ed3.

2024-07-04 08:34 UTC, damianooldoni commented on NAMESPACE
> +importFrom(memoise,memoise)
Good catch! No, indeed. Removed in 506e8e6.

2024-07-04 08:39 UTC, damianooldoni commented
@PietrH: indeed, we expect at this stage a lot of test failures as we are just started the transition.

But the important stuff is that the following tests are not failing:

```r
> devtools::test(filter = "read_camtrapdp")
ℹ Testing camtraptor
✔ | F W  S  OK | Context
✔ |          2 | read_camtrapdp [2.0s]                                                                     

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 2.1 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]
```

2024-07-04 08:39 UTC, merged