Use filter functions/remove args from functions
inbo/camtraptor pull request #331
Opened 2024-07-25 10:50 UTC by damianooldoni

This PR solves few issues at the same time as it was difficult to disentangle them.

- Deprecate `map_dep()`, create `map_deployments()`  (#231). Deprecate also the args `sex` and `life_stage` of `map_dep()`. Why deprecate args of a deprecated function? Because the proposed new solutions are different: the deprecated arguments are not replaced by some args in `map_deployments()`: the user need to filter via `filter_observations()`.
- Use the reexported filtering functionality `filter_observations()` in (deprecated) `map_dep(sex, life_stage)`. Also update all examples where we show how to filter by sex and life stage via `filter_observations()`.
- Make predicate functions defunct (#316): they were just abruptly removed in PR #321.
- Deprecate `get_n_species`, create `n_species()` (#243).
- Deprecate `get_cam_op()`, create `camtrapR_cameraOperation()` (#239).
- Deprecate `get_record_table()`, create `camtrapR_recordTable()` (#240).
- Update related tests file: new filenames, new function names, new tests for deprecations.
- Reexport the pipe from dplyr, as we did in camtrapdp (#330)
- Remove `round_coordinates()` (#327)
- Use `purrr::pluck()` where needed (#326)  
- Update, improve and compile documentation (`devtools::document()`)

2024-08-05 13:31 UTC, sannegovaert requested changes
Wow, that is a big PR :-)

The issues you listed seem to be solved, so that's great.
I fixed some small issues related to typo's and parameter names.
But many functions, examples and tests are not working because of some bigger issues:
- `sequenceID` need to be removed/replaced
- vernacular names do not work in some functions
- the tests of class `lifecycle_warning_deprecated` do not work

2024-08-28 12:03 UTC, damianooldoni commented
Thanks @sannegovaert! 
Yes, many tests still fail, but it's normal. We decided to do the update to v1 step by step and it's quite impossible to adapt all tests at this stage. I changed only the tests which were relevant for this PR. Other tests will be updated while working on the core of the related functions, e.g. see #332.

I will screen and reply to your comments, one by one, of course.

2024-09-12 08:21 UTC, damianooldoni commented on R/map_deployments.R
> +                    species = NULL,
This will be tackled in a specific PR.

2024-09-12 08:30 UTC, damianooldoni commented on R/map_deployments.R
> +#' species, number of observations and RAI on a dynamic map.
Done in [bea171f](https://github.com/inbo/camtraptor/pull/331/commits/bea171fd397f22f661af7e4569cedb4d4fcab13f) 👍

2024-09-12 08:30 UTC, damianooldoni commented on R/map_deployments.R
> +#' species, number of observations and RAI on a dynamic map.
I will run `devtools::document()` at the end.

2024-09-12 08:33 UTC, damianooldoni commented on NEWS.md
> +- `round_coordinates()` has moved to [camtrapdp](https://inbo.github.io/camtrapdp/reference/round_coordinates.html) (#327).
No, I don't think that's the plan. `camtraptor` hasn't that scope anymore. Only exploratory and visualization.

2024-09-12 08:55 UTC, damianooldoni commented on tests/testthat/test-map_deployments.R
> +    lifecycle_warning_deprecated
Found `lifecycle::expect_deprecated` which works specifically with lifecycle deprecation warnings. In console:
```r
> testthat::test_that("map_dep() is deprecated", {
+     testthat::skip_if_offline()
+     x <- example_dataset()
+     lifecycle::expect_deprecated(map_dep(x, "n_species"))
+ })
Test passed
```
Test modified in [7e181a3](https://github.com/inbo/camtraptor/pull/331/commits/7e181a3f4786c12591bf57fa41f9cbdaa0a491fd)

2024-09-12 08:57 UTC, damianooldoni commented on R/camtrapR_recordTable.R
> +#' x_dup$data$observations[4,"sequenceID"] <- purrr::pluck(
I know. It will be tackled in a specific PR. This PR is big enough 😄

2024-09-12 09:08 UTC, damianooldoni commented on R/get_scientific_name.R
> +    x <- example_dataset
Using `example_dataset()` if nothing is not the wished behavior.

See `get_scientific_name()` in `main`:

```r
get_scientific_name <- function(package = NULL,
                                vernacular_name,
                                datapkg = lifecycle::deprecated()) {
check_package(package, datapkg, "get_scientific_name")
  if (is.null(package) & !is.name(datapkg)) {
    package <- datapkg
  }
```
The idea here was to use datapkg (deprecated) if package was not given.

Still, thanks to you I see that I have to remove this `if ()` statement 👍
Moreover, this function will disappear in one of the next PRs. See #235.
Done in

2024-09-12 09:12 UTC, damianooldoni commented on tests/testthat/test-camtrapR_cameraOperation.R
> +      as.Date(deployments(x1)$deployments$deploymentEnd[2]) - lubridate::ddays(1)
To be tackled in another PR when the function will be refactored.

2024-09-12 10:13 UTC, damianooldoni commented on tests/testthat/test-camtrapR_cameraOperation.R
> +  expect_warning(get_cam_op(x), lifecycle_warning_deprecated)
Done in [ac9e1c0](https://github.com/inbo/camtraptor/pull/331/commits/ac9e1c0fc058cf8ae0c2fe4a8f302dcce95976b9)

2024-09-12 10:14 UTC, damianooldoni commented on tests/testthat/test-camtrapR_cameraOperation.R
> +    as.Date(max(purrr::pluck(deployments(x), "deploymentEnd"))),
It has to do with new input. To be tackled while working on the function. So, something for another PR.

2024-09-12 10:16 UTC, damianooldoni commented on tests/testthat/test-camtrapR_recordTable.R
> +    camtrapR_recordTable(x,
This PR is not aimed to update this function. So, tests will fail of course. Something for another PR soon.

2024-09-12 10:37 UTC, damianooldoni commented on tests/testthat/test-get_n_individuals.R
> -
This can be fixed now, indeed.
Using `taxa()` in `get_n_individuals()` helps: `species <- taxa(x)$scientificName`. Solved in 6c5d69d.
The deployment ID used in test was outdated (old input data).
Solved in 69f6965.

2024-09-12 11:16 UTC, damianooldoni commented on tests/testthat/test-map_deployments.R
> +test_that("Check all three deprecations: function and args sex and life_stage", {
Several things found and solved in 25b4b48.

2024-09-12 11:36 UTC, damianooldoni commented on NEWS.md
> +- Function `get_record_table()` has been deprecated. Use `camtrapR_recordTable()` (#240).
Done in ab40dc2, 0a24cc2. Thanks. We will have to check the news again many times and for sure before version 1.0 is released.

2024-09-12 11:44 UTC, damianooldoni commented on R/defunct.R
> +#' @name defunct
The `NULL` means that it applies to all functions following below.
See dplyr: https://github.com/tidyverse/dplyr/blob/main/R/defunct.R

2024-09-12 11:47 UTC, damianooldoni commented on R/get_custom_effort.R
> +#' also calculated over all deployments. This function calls `camtrapR_cameraOperation()`
This is something related to input data. When I work on `get_custom_effort()` I will for sure adapt the examples.

2024-09-12 11:49 UTC, damianooldoni commented on R/map_deployments.R
> +#' # Show number of observations (observations of unidentified species included
Same here. Checking the internal working of the functions based on new camtrap data format will be for a separate PR.

2024-09-12 11:56 UTC, damianooldoni commented on R/get_n_individuals.R
> +#' # Use `filter_observations()` to filter on life stage
It has to do with https://github.com/inbo/camtraptor/issues/235. I will tackle this in another PR. The support of vernacular names in these functions will be removed as we can do it combining `taxonomy()` with `filter_observations()`.

2024-09-12 11:57 UTC, damianooldoni commented on R/camtrapR_recordTable.R
> +#' camtrapR_recordTable(
Function will be tackled in another PR.

2024-09-12 11:58 UTC, damianooldoni commented on tests/testthat/test-get_rai.R
> +  # Columns `deploymentID`, `scientificName` and `rai` only
I will work on function `get_rai()` in another PR.

2024-09-12 12:05 UTC, damianooldoni commented on tests/testthat/test-camtrapR_recordTable.R
> +    lifecycle_warning_deprecated)
Fix using `lifecycle::expect_deprecated()` as updated in other tests too. Still, the test fails because `get_record_table(x)` returns an error due to `sequenceID` column not existing. This will be fixed in other PR soon.

2024-09-18 08:13 UTC, sannegovaert commented
Thanks for addressing everything, Damiano!
I just replaced another `lifecycle_warning_deprecated`.
All seems good to go now!

2024-09-18 15:26 UTC, damianooldoni commented
Hi @sannegovaert, thanks for checking again. Can you officially approve the PR? Thanks.

2024-09-19 07:13 UTC, sannegovaert approved these changes

2024-09-19 07:40 UTC, merged