Finalize `n_species`, deprecate/defunct other functions, add `CITATION.cff`
inbo/camtraptor pull request #346
Opened 2024-11-20 16:26 UTC by damianooldoni

This pull request includes several changes to the codebase, focusing on:
- finalizing `n_species()` and its tests
- deprecating some functions
- improving documentation

### Finalizing `n_species()` and its tests

Up to now, tests were not really taken into account as we were way far from getting the functions ready to the new format. From this PR we can start using them 🥳 as the very first function, `n_species()`, is ready! So, please run `devtools::test(filter = "n_species")` as check. Its related tests have been simplified without losing testing power.

### Deprecation of functions

* Deprecated the `get_species()` function in favor of `taxa()` (fix #343)
* `get_scientific_name()` and `check_species()` functions are defunct in favor of `taxa()` (fix #235). So, `check_species()` and `get_scientific_name()` functions are moved to `defunct.R`.

## Metadata

* Added `CITATION.cff` (fix #345) (using `cffr::cff_write()`).

### Documentation updates

* Updated references in multiple R files to inherit arg description from `n_species` instead of the deprecated `get_species`. This has been done by using `@inheritParams n_species` instead of `@inheritParams get_n_species`.
* Updated the `NEWS.md` file to reflect the deprecation/defunct of several functions, the introduction of new replacements and new citation file.

### Code Cleanup

* Simplified the `get_n_individuals()` function by removing the `species` parameter and associated logic: we do not filter anymore within such functions, only via `filter_observations()`.

2024-11-21 16:16 UTC, sannegovaert requested changes
Nice!
I have  1 remark about filtering on observationLevel & a suggestion for simplification.

2024-11-21 16:16 UTC, sannegovaert commented on R/n_species.R
> +  observations <- observations(x) %>%
I suggest:
`x <- filter_observations(.data$observationLevel == "event")` 
and using `observations(x)` instead of `observations`.

Because what if there is a deployment with only media-based observations?
It would now not be noticed in L33: `deployments_no_obs <- get_dep_no_obs(x)`.

And last, why is the count reduced by NA-values in a mutate-function, and not like this?:
 ```
n_species <-
    species %>% 
    dplyr::filter(!is.na(.data$scientificName)) %>% 
    dplyr::group_by(.data$deploymentID) %>%
    dplyr::count() %>%
    dplyr::ungroup()
```

2024-12-13 14:15 UTC, damianooldoni commented on R/n_species.R
> +  observations <- observations(x) %>%
Fully agree with first suggestion 🔝  Implemented in 28ae966 and 328a573.
About the reason why I use a mutate to not count NA as species: I agreed with you at the beginning , but then thanks to a failing test (A perfect example of the need of unit-tests!) I found the reason I wrote that few years ago 😄 We need to assign 0 to deployments with ONLY unidentified species (`scientificName` = `NA`). To do that, the shortest way I found was to do a standard `group_by() %>% count()` and then reducing the sum by one. I improved the comments in the code to better understand this for future-me and everybody else.

2024-12-13 14:17 UTC, damianooldoni commented
I also ordered the output by using the original order as provided in deployment table. Tests added to check this.

Also added a test to check that deployments without event-based observations have `n = NA` as for deployments without any observation at all.

2024-12-18 13:58 UTC, sannegovaert approved these changes
Well done, I have no comments!

2024-12-24 09:11 UTC, merged